'use client';
import { useEffect, useState } from 'react';
import type { Book, Question, Tone, Workspace } from '@/lib/types';
import { editDraft, finalise, freshWorkspace, readWorkspace, storageKey } from '@/lib/workspace';
import { ResearchViews } from './ResearchViews';
import Editor from './Editor';
import ChairPreview from './ChairPreview';
import MeetingCapture from './MeetingCapture';
import Roundup from './Roundup';
import {admitResearchCandidate} from '@/lib/research-promotions';
const steps=['Admin Briefing','Context & Interpretation','Candidate Collisions','Draft Opinion Map','Chair / member preview','Meeting Capture','Round-up preview'];
export default function AdminApp({books}:{books:Book[]}){
 const [bookId,setBookId]=useState(books[0].id);const book=books.find(b=>b.id===bookId)!;
 const [state,setState]=useState<Workspace>(()=>freshWorkspace(book)),[step,setStep]=useState(0),[notice,setNotice]=useState(''),[saved,setSaved]=useState('Loading local workspace…'),[ready,setReady]=useState(false);
 useEffect(()=>{let cancelled=false;const boot=()=>{try{const raw=localStorage.getItem(storageKey(book.id));if(!cancelled){setState(raw?readWorkspace(raw,book):freshWorkspace(book));setSaved(raw?'Loaded from this browser':'Ready · browser-local storage');}}catch{if(!cancelled){setState(freshWorkspace(book));setSaved('Saved data could not be loaded');setNotice('Showing the original fixture. Existing saved data has not been overwritten.');}}if(!cancelled)setReady(true);};boot();return()=>{cancelled=true;};},[book]);
 function update(next:Workspace){setState(next);try{localStorage.setItem(storageKey(book.id),JSON.stringify(next));setSaved('Saved in this browser');}catch{setSaved('Not saved — storage unavailable');setNotice('Changes are in memory only. Export a backup before closing.');}}
 function commit(questions:Question[],reason:string,tone?:Tone){try{const next=editDraft(state,book,questions,reason);if(tone)next.tone=tone;update(next);setNotice(next.diagnostics.valid?'Draft saved. Structural checks pass.':'Draft saved. Review the editorial issues.');}catch(e){setNotice((e as Error).message);}}
 function finish(){try{update(finalise(state,book));go(4);}catch(e){setNotice((e as Error).message);}}
 function promote(candidateId:string){try{const questions=admitResearchCandidate(state.draft,book.id,candidateId);const next=editDraft(state,book,questions,'Admitted verified research wording');update(next);setNotice('Verified research wording added to the draft. Editing it will expire the verification link.');setStep(3);window.scrollTo(0,0);}catch(e){setNotice((e as Error).message);}}
 function go(n:number){setStep(n);setNotice('');window.scrollTo(0,0);}
 function exportBackup(){const blob=new Blob([JSON.stringify({book_id:book.id,workspace:state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${book.id}-workspace.json`;a.click();URL.revokeObjectURL(url);}
 async function importBackup(file:File|undefined){if(!file)return;try{if(file.size>2000000)throw Error('Backup is too large.');const raw=JSON.parse(await file.text());if(raw.book_id!==book.id)throw Error('Select the matching book before importing.');const next=readWorkspace(JSON.stringify(raw.workspace),book);update(next);setNotice('Workspace restored from backup.');}catch(e){setNotice(`Import failed: ${(e as Error).message}`);}}
 return <><aside className="sidebar"><a className="brand" href="/">bcb<span>BOOK CLUB<br/>BRIEFING</span></a><p className="eyebrow">YOUR WORKSPACE</p><label htmlFor="book">Selected book</label><select id="book" value={bookId} onChange={e=>{setReady(false);setBookId(e.target.value);setNotice('');}}>{books.map(b=><option key={b.id} value={b.id}>{b.book_title}</option>)}</select><nav aria-label="Workflow">{steps.map((s,i)=><button key={s} className={step===i?'active':''} aria-current={step===i?'page':undefined} onClick={()=>go(i)}>{String(i+1).padStart(2,'0')} &nbsp; {s}</button>)}</nav><div className="sidebar-foot">V1.1 · Research pilot<br/>Verified evidence + fixture editor<br/>Saved in this browser</div></aside><main><header><span className="eyebrow">ADMIN STUDIO</span><span id="save-state" role="status">{saved}</span></header><div id="heading"><span className="eyebrow">{book.author}</span><h1>{book.book_title}</h1><p className="subtitle muted">{steps[step]} <span className="tag">{state.final?'Chair version saved':'Draft workspace'}</span> <span className="tag">Full spoilers</span></p></div><div id="notice" role="status" aria-live="polite">{notice}</div>{!ready?<p>Loading your saved workspace…</p>:<section id="content">{step<3&&<ResearchViews book={book} questions={state.draft} view={step} go={go} onPromote={promote}/>} {step===3&&<Editor key={book.id} book={book} state={state} commit={commit} update={update} finish={finish} notify={setNotice}/>} {step===4&&<ChairPreview book={book} questions={state.final?.questions??state.draft} date={state.final?.date}/>} {step===5&&<MeetingCapture key={book.id} book={book} questions={state.final?.questions??null} meeting={state.meeting} update={meeting=>update({...state,meeting})} go={go} notify={setNotice}/>} {step===6&&<Roundup book={book} questions={state.final?.questions??null} meeting={state.meeting} update={meeting=>update({...state,meeting})} go={go}/>}<details className="no-print backup"><summary>Workspace backup & portability</summary><p className="hint">Each browser, port and hosting address has separate storage. Export this book’s workspace to move it. Import replaces the selected book’s current workspace; export first if you want to keep both.</p><button onClick={exportBackup}>Export workspace JSON</button><label htmlFor="backup-file">Restore this book from a backup</label><input id="backup-file" type="file" accept="application/json,.json" onChange={e=>{void importBackup(e.target.files?.[0]);e.target.value='';}}/></details></section>}</main></>;
}
