import { useState } from 'react';
import type { Book, Meeting, Question, Score } from '@/lib/types';
import { createMeeting, recordPosition, scoreLabels, scoreValues } from '@/lib/meeting';
interface Props {book:Book;questions:Question[]|null;meeting:Meeting|null;update:(m:Meeting)=>void;go:(n:number)=>void;notify:(s:string)=>void}
export default function MeetingCapture({book,questions,meeting,update,go,notify}:Props){
 const [names,setNames]=useState('Anne, Bill, Carol, David, Ellie, Fran'),[date,setDate]=useState(''),[index,setIndex]=useState(0),[grid,setGrid]=useState(false),[phase,setPhase]=useState<'initial'|'final'>('initial');
 if(!questions)return <div className="empty"><h2>Prepare the Chair version first</h2><p>Finalise the draft before recording positions against a fixed set of questions.</p><button className="primary" onClick={()=>go(3)}>Review draft</button></div>;
 if(!meeting){const start=(sample:boolean)=>{try{update(createMeeting(book,questions,names.split(',').map(x=>x.trim()).filter(Boolean),date,sample));}catch(e){notify((e as Error).message);}};return <article className="card"><h2>Prepare a meeting</h2><p>Try fictional responses, or start with blank entries. Both stay in this browser.</p><label htmlFor="members">Attendees (comma separated; up to 12)</label><input id="members" value={names} onChange={e=>setNames(e.target.value)}/><label htmlFor="date">Meeting date</label><input id="date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><div className="actions"><button className="primary" onClick={()=>start(true)}>Load simulated meeting</button><button onClick={()=>start(false)}>Start blank capture</button></div></article>;}
 const qs=questions.filter(q=>q.question_type==='five_point'),q=qs[index]??qs[0];
 const record=(qid:string,member:number,score:Score)=>update(recordPosition(meeting,qid,member,phase,score));
 return <><div className="banner">{meeting.simulated?'Simulated meeting · fictional responses':'Local meeting capture'} · {meeting.date||'Date not set'}<br/>Recording against the saved Chair version. Blank entries never count as the middle.</div><div className="actions"><button onClick={()=>setGrid(false)}>Question view</button><button onClick={()=>setGrid(true)}>Review grid</button><label htmlFor="phase">Position</label><select id="phase" value={phase} onChange={e=>setPhase(e.target.value as 'initial'|'final')}><option value="initial">Initial</option><option value="final">After discussion (optional)</option></select><button onClick={()=>go(6)}>Review Round-up →</button></div>{grid?<article className="card table-wrap"><table><thead><tr><th>Member</th>{qs.map((q,i)=><th key={q.id} title={q.proposition}>Q{i+1}{meeting.skipped[q.id]?' · skipped':''}</th>)}</tr></thead><tbody>{meeting.members.map((name,mi)=><tr key={name}><th>{name}</th>{qs.map(q=><td key={q.id}><select aria-label={`${name}: ${q.proposition}`} value={meeting.responses[q.id][mi][phase]} onChange={e=>record(q.id,mi,e.target.value as Score)}>{scoreValues.map(v=><option key={v} value={v}>{v===''&&phase==='final'?'Unchanged / not recorded':scoreLabels[v]}</option>)}</select></td>)}</tr>)}</tbody></table><p className="hint">Blank after-discussion entries retain the initial position. Initial missing entries stay missing.</p></article>:<article className="card"><label htmlFor="question">Question</label><select id="question" value={index} onChange={e=>setIndex(Number(e.target.value))}>{qs.map((q,i)=><option key={q.id} value={i}>{i+1}. {q.proposition}</option>)}</select><h2 className="spaced">{q.proposition}</h2><p>{q.subtext}</p><label className="check"><input type="checkbox" checked={!!meeting.skipped[q.id]} onChange={e=>{const next=structuredClone(meeting);next.skipped[q.id]=e.target.checked;delete next.insights[q.id];update(next);}}/>Not discussed — omit from Round-up</label>{meeting.skipped[q.id]?<p>Saved entries are retained but excluded while this question is skipped.</p>:meeting.members.map((name,mi)=><div className="score-row" key={name}><strong>{name}</strong><div className="score-buttons" role="group" aria-label={`${name} position`}>{scoreValues.map(v=><button key={v} className={meeting.responses[q.id][mi][phase]===v?'chosen':''} aria-pressed={meeting.responses[q.id][mi][phase]===v} onClick={()=>record(q.id,mi,v)}>{v===''&&phase==='final'?'Unchanged':scoreLabels[v]}</button>)}</div></div>)}<label htmlFor="note">Optional Admin note (not used to infer anyone’s reasons)</label><textarea id="note" value={meeting.notes[q.id]??''} onChange={e=>update({...meeting,notes:{...meeting.notes,[q.id]:e.target.value}})}/><div className="actions"><button disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous</button><button disabled={index===qs.length-1} onClick={()=>setIndex(index+1)}>Next →</button></div></article>}</>;
}
