import ResearchPilot from './ResearchPilot';
import BookReviews from './BookReviews';
import { STEP_DRAFT, STEP_CONTEXT, STEP_COLLISIONS } from '@/lib/steps';
import type { Book, Question } from '@/lib/types';
export function Evidence({book,question}:{book:Book;question:Question}){
 const c=book.collisions.find(c=>c.id===question.collision_id);if(!c)return <p>Optional wider question from the original book fixture. It is not scored.</p>;
 return <><p><strong>{c.title}</strong></p><div className="grid"><p><b>One view</b><br/>{c.lens_a}</p><p><b>Another view</b><br/>{c.lens_b}</p></div><p className="hint">{c.evidence_strength} · {c.id}</p>{c.finding_ids.map(id=>{const f=book.findings.find(f=>f.id===id);return <p className="hint" key={id}><b>{id}</b><br/>{f?.text}<br/>{f?.source}</p>;})}</>;
}
export function ResearchViews({book,questions,view,go,onPromote}:{book:Book;questions:Question[];view:number;go:(n:number)=>void;onPromote?:(candidateId:string)=>void}){
 if(view===0)return <><ResearchPilot bookId={book.id} onPromote={onPromote}/><div className="banner"><strong>Sample briefing</strong><br/>Sample discussion material. These are possible views, not findings from reader research.</div><article className="card"><h2>A way into the conversation</h2><p>{book.summary}</p><div className="stats"><div><strong>{questions.filter(q=>!q.optional).length}</strong><span>statements to rate</span></div><div><strong>{book.collisions.length}</strong><span>candidate collisions</span></div><div><strong>{book.lenses.length}</strong><span>discussion themes</span></div></div><div className="actions"><button className="primary" onClick={()=>go(STEP_DRAFT)}>Open the draft →</button><button onClick={()=>go(STEP_CONTEXT)}>Explore context</button></div></article><div className="grid"><article className="card"><h3>Editorial focus</h3>{book.lenses.length?<>{[book.lenses[0],book.lenses[2]].filter(Boolean).map((l,i)=><p key={i}>{l!.why_it_matters}</p>)}</>:<p className="hint">No discussion themes have been authored for this book yet.</p>}</article><article className="card"><h3>Research gaps</h3><p>These sample briefing sections have not been validated against the reviews. The separate research pilot above reports its own findings and unresolved checks.</p><p className="hint">The source notes refer to sample material, not published reviews.</p></article></div><article className="card"><h3>Your workspace</h3><p>Drafts and meeting entries are saved separately for each book in this browser. Finalising creates a fixed Chair version. The Chair chooses what to circulate and discuss.</p><p className="hint">Curator controls remain simulated. Nothing is shared automatically.</p></article></>;
 if(view===1)return <BookReviews book={book}/>;
 if(view===2)return <><p className="muted">Possible ways to discuss the book. These are suggestions, not claims about what readers generally think.</p>{book.lenses.map(l=><article className="card" key={l.title}><span className="tag">{l.lens_type} · fixture</span><h2>{l.title}</h2><div className="grid"><div><h3>The idea</h3><p>{l.core_idea}</p><h3>Why it matters here</h3><p>{l.why_it_matters}</p></div><div><h3>What to consider</h3><p>{l.what_it_changes}</p><h3>Where interpretations differ</h3><p>{l.disagreement}</p></div></div><p className="hint">Opinion Map connections: {l.collision_ids.join(' · ')}</p><button onClick={()=>go(STEP_COLLISIONS)}>Inspect candidate collisions</button></article>)}</>;
 return <><p className="muted">Ten possible disagreements to discuss. Replacing a card changes its topic; rewording keeps the same topic.</p><div className="grid">{book.collisions.map(c=><article key={c.id} className="card"><span className="tag">{c.dimension}</span><span className="tag">{questions.some(q=>q.collision_id===c.id)?'In draft':'Available'}</span><h3>{c.title}</h3><p>{c.lens_a} <b>↔</b> {c.lens_b}</p><p className="hint">{c.evidence_strength}</p><details><summary>Source notes and discussion wording</summary><Evidence book={book} question={c.question}/><p>{c.question.proposition}</p></details></article>)}</div></>;
}

